version: '3'
services:
  rootmebot:
    build: .
    restart: always
    environment:
      - BOT_CHANNEL=activity
      - TOKEN=token
      - ROOTME_API_KEY=Your Root-Me API key found on your Root-Me profile
    volumes:
      - ./data/:/app/data
